# SmartSupport System v2.7.2 - Docker Compose
# ЧСВ Team (16.10.2025)
version: '3.8'

services:
  smartsupport:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: smartsupport_v2.7.2
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/api/version')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

